---
title: "tensor plot"
author: "Iris Griffith"
date: "6/21/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
library(ggplot2)
library(purrr)
library(dplyr)
library(tidyverse)
library(rmutil)
library(tensor)
library(scales)
source('https://raw.githubusercontent.com/diff-priv-ht/ANOVA-Group/master/Code/R%20code/R/datagen.R?token=AeAa3YlvA4FuDWcBEb9zfFjtKAEktgOqks5bjh7iwA%3D%3D', echo=FALSE)
source('https://raw.githubusercontent.com/diff-priv-ht/ANOVA-Group/master/Code/R%20code/R/ggplot_theme.R?token=AeAa3Y14yJtVX39GdK5dfyZkEbs3M77Qks5bjh8qwA%3D%3D', echo=FALSE)
source('https://raw.githubusercontent.com/diff-priv-ht/ANOVA-Group/master/Code/R%20code/R/helpers.R?token=AeAa3b71_HFAGlkpAdQ3JYt6SoPat3TZks5bjh9NwA%3D%3D', echo=FALSE)
source('https://raw.githubusercontent.com/diff-priv-ht/ANOVA-Group/master/Code/R%20code/R/power_calc.R?token=AeAa3XDD7X9RgE7INdceLtzufMhKQLfTks5bjh9pwA%3D%3D', echo=FALSE)
source('https://raw.githubusercontent.com/diff-priv-ht/ANOVA-Group/master/Code/R%20code/R/stat_functions.R?token=AeAa3bvXCCClhPiibKASw6VCr8Ye4KVrks5bjh-AwA%3D%3D', echo=FALSE)
```

```{r,eval = FALSE, warning=FALSE}
mus <- c(.475,.5,.525)
effect_size <- (seq(from = 1, to = 10, by = 1)) %>% map(~ (mus-median(mus))*. + median(mus))
sigmas <- seq(from = .010, to = .19, by = .015)
epsilons <- 1
reps <- 400
Ns <- seq(from = 30, to = 1020, by = 3*30)
  
  variables <- cross2(effect_size, sigmas) %>% unlist %>% matrix(ncol = 4, byrow = TRUE)
  sigmas2 <- variables[,4]
  effect_size2 <- split(t(variables[,1:3]), rep(1:nrow(variables), each = 3))
  set.seed(1)
    N_effect_sigma1 <- map2(.x = effect_size2, .y = sigmas2, ~ power_plot_estimated_optimized(Ns = Ns, mus = .x, sigma = .y, epsilons = 1, Statistic = "absFstat", p = NULL, reps, frac = .75))
  set.seed(1)
    N_effect_sigma2 <- map2(.x = effect_size2, .y = sigmas2, ~ power_plot_estimated_optimized(Ns = Ns, mus = .x, sigma = .y, epsilons = 1, Statistic = "absVarstat", p = NULL, reps, frac = .35))
```

```{r}
threshold <- function(x, thresh= .8){
  ifelse(x > thresh , x, 0)
}

final1 <- rep(NA,length(Ns)*(length(effect_size))) %>% matrix(nrow = length(Ns)) %>% tensor(rep(1,length(sigmas)))
    final2 <- final1
      # first margin Ns, second margin effect_size, third margin sigmas
    intermediate1 <- 1:length(Ns) %>% tensor(rep(1,length(sigmas2)))
    intermediate2 <- intermediate1

for(i in 1:length(sigmas2)){
  intermediate1[,i] <- ((N_effect_sigma1[[i]][,2] %>% lapply(threshold, thresh = .8)) %>% unlist)
  intermediate2[,i] <- ((N_effect_sigma2[[i]][,2] %>% lapply(threshold, thresh = .8)) %>% unlist)
}
for(j in 1:length(sigmas)){
  final1[,,j] <- intermediate1[,((j-1)*10+1):(j*10)]
  final2[,,j] <- intermediate2[,((j-1)*10+1):(j*10)]
} 
    
```

```{r}
tensor_plot <- function(tensor, tensor2, margin = 3, marginlabs = c("1","2","3")){ # takes a 3 tensor and plots slices of heatmaps
  out <- list()
 if (margin == 3){
   for(i in 1:dim(tensor)[3]){
     index_1 <- dim(tensor)[1]
     index_2 <- dim(tensor)[2]
     d <- data.frame(rowvec = rep(1:index_1, rep(index_2, index_1)),
                     colvec = rep(1:index_2, index_1),
                     power1 = tensor[,,i] %>% t() %>% as.vector(),
                     power2 = tensor2[,,i] %>% t() %>% as.vector()) %>%
        mutate(`Statistics with high power` = 
                 ifelse(!power1 & !power2, "neither",
                        ifelse(power1 & !power2, "absF",
                               ifelse(!power1 & power2, "absvarF", "both"))))
      out[[i]] <- ggplot(d, aes(x = colvec, y = rowvec)) +
        geom_tile(aes(fill = `Statistics with high power`)) +
        scale_fill_manual(values = c("neither" = "darkgray", 
                                     "absF"    = "red", 
                                     "absvarF" = "blue", 
                                     "both"    = "purple")) +
        theme_bw() +
        ggtitle(paste(marginlabs[3],"slice", i)) +
        xlab(marginlabs[2]) +
        ylab(marginlabs[1])
    }
  }
   if (margin == 2){
   for(i in 1:dim(tensor)[2]){
     index_1 <- dim(tensor)[3]
     index_2 <- dim(tensor)[1]
     d <- data.frame(rowvec = rep(1:index_1, rep(index_2, index_1)),
                     colvec = rep(1:index_2, index_1),
                     power1 = tensor[,i,]  %>% as.vector(),
                     power2 = tensor2[,i,] %>% as.vector()) %>%
        mutate(`Statistics with high power` = 
                 ifelse(!power1 & !power2, "neither",
                        ifelse(power1 & !power2, "absF",
                               ifelse(!power1 & power2, "absvarF", "both"))))
      out[[i]] <- ggplot(d, aes(x = colvec, y = rowvec)) +
        geom_tile(aes(fill = `Statistics with high power`)) +
        scale_fill_manual(values = c("neither" = "darkgray", 
                                     "absF"    = "red", 
                                     "absvarF" = "blue", 
                                     "both"    = "purple")) +
        theme_bw() +
        ggtitle(paste(marginlabs[2],"slice", i)) +
        xlab(marginlabs[1]) +
        ylab(marginlabs[3])
    }
  }
   if (margin == 1){
   for(i in 1:dim(tensor)[1]){
     index_1 <- dim(tensor)[2]
     index_2 <- dim(tensor)[3]
     d <- data.frame(rowvec = rep(1:index_1, rep(index_2, index_1)),
                     colvec = rep(1:index_2, index_1),
                     power1 = tensor[i,,] %>% t() %>% as.vector(),
                     power2 = tensor2[i,,] %>% t() %>% as.vector()) %>%
        mutate(`Statistics with high power` = 
                 ifelse(!power1 & !power2, "neither",
                        ifelse(power1 & !power2, "absF",
                               ifelse(!power1 & power2, "absvarF", "both"))))
      out[[i]] <- ggplot(d, aes(x = colvec, y = rowvec)) +
        geom_tile(aes(fill = `Statistics with high power`)) +
        scale_fill_manual(values = c("neither" = "darkgray", 
                                     "absF"    = "red", 
                                     "absvarF" = "blue", 
                                     "both"    = "purple")) +
        theme_bw() +
        ggtitle(paste(marginlabs[1],"slice", i)) +
        xlab(marginlabs[3]) +
        ylab(marginlabs[2])
    }
  }
  print(out)
}
```

```{r}
      # first margin Ns, second margin effect_size, third margin sigmas
tensor_plot(final1, final2, margin = 2, marginlabs = c("database size", "effect size", "sigma"))

#INSTRUCTIONS FOR ANDREW/ADAM: load gyoza2.RData and then run the above function in this chunk first! 
#in order to change the axes to reflect a correct value, see if you can find the linear transformation
#that corresponds to taking the indecies to their corresponding values.
#Andrew: The lapply function doesn't work with ggplot '+' operator, so you need to manually pick whichever slice you want at a time and then select it with [[]] and then add the ggplot functions below.
#lastly, the three vectors/lists below are what the indecies correspond to.

Ns #dbsize
sigmas #sigmas
effect_size #effect size

#example linear transformation
scale_x_continuous(labels = function(x) 0.05*(x-1) + .2) +
  scale_y_continuous(labels = function(x) 0.02*(x-1) + .01) +
  labs(fill = "Statistic with Power above 0.8") 
```